# Generated by Django 6.0.6 on 2026-06-24 21:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('name', models.CharField(max_length=200, unique=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('qa', 'QA'), ('instructor', 'Instructor'), ('student', 'Student'), ('admission', 'Admission'), ('dept_admin', 'Department Admin'), ('admin', 'Admin')], default='', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='core_users', related_query_name='core_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='core_users', related_query_name='core_user', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InstructorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(max_length=100)),
                ('course_type', models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab')], default='Theory', max_length=10)),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('credit_hours', models.IntegerField(default=3)),
                ('clo_count', models.IntegerField(default=4)),
                ('selected_grading_system', models.CharField(choices=[('ready1', 'Standard Absolute'), ('ready2', 'Alternative Absolute'), ('custom', 'Custom')], default='ready1', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_courses', to='core.department')),
            ],
            options={
                'verbose_name': 'Instructor Course',
                'verbose_name_plural': 'Instructor Courses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=60)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.instructorcourse')),
            ],
            options={
                'verbose_name': 'Course Student',
                'verbose_name_plural': 'Course Students',
                'ordering': ['reg_no'],
                'unique_together': {('course', 'reg_no')},
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor Profile',
                'verbose_name_plural': 'Instructor Profiles',
            },
        ),
        migrations.AddField(
            model_name='instructorcourse',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_courses', to='core.instructorprofile'),
        ),
        migrations.CreateModel(
            name='MarksCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.FloatField(default=0)),
                ('units', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.instructorcourse')),
            ],
            options={
                'verbose_name': 'Marks Category',
                'verbose_name_plural': 'Marks Categories',
                'ordering': ['order'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='core.department')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='instructorcourse',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructor_courses', to='core.program'),
        ),
        migrations.CreateModel(
            name='GraduateAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduate_attributes', to='core.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduate_attributes', to='core.program')),
            ],
            options={
                'verbose_name': 'Graduate Attribute',
                'verbose_name_plural': 'Graduate Attributes',
                'ordering': ['ga_id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective')], default='core', max_length=10)),
                ('credit_hours', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.department')),
                ('mapped_gas', models.ManyToManyField(blank=True, related_name='courses', to='core.graduateattribute')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.program')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('batch', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Fall', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_students', to='core.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_students', to='core.program')),
            ],
            options={
                'verbose_name': 'Admission Student',
                'verbose_name_plural': 'Admission Students',
                'ordering': ['reg_no'],
            },
        ),
        migrations.CreateModel(
            name='ProgramObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='core.program')),
            ],
            options={
                'verbose_name': 'Program Objective',
                'verbose_name_plural': 'Program Objectives',
                'ordering': ['code'],
                'unique_together': {('program', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_staff', to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qa_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QA Profile',
                'verbose_name_plural': 'QA Profiles',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('batch_year', models.IntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['roll_number'],
            },
        ),
        migrations.CreateModel(
            name='UnitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.IntegerField()),
                ('passing', models.FloatField(default=5)),
                ('total_marks', models.FloatField(default=10)),
                ('weightage', models.FloatField(default=0)),
                ('mapped_clos', models.JSONField(default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_items', to='core.markscategory')),
            ],
            options={
                'verbose_name': 'Unit Item',
                'verbose_name_plural': 'Unit Items',
                'ordering': ['unit_no'],
                'unique_together': {('category', 'unit_no')},
            },
        ),
        migrations.CreateModel(
            name='OBEQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('unit_no', models.IntegerField()),
                ('question_name', models.CharField(max_length=200)),
                ('max_marks', models.FloatField(default=0)),
                ('mapped_clos', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obe_questions', to='core.instructorcourse')),
                ('unit_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.unititem')),
            ],
            options={
                'verbose_name': 'OBE Question',
                'verbose_name_plural': 'OBE Questions',
                'ordering': ['order'],
                'unique_together': {('course', 'frontend_id')},
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('min_percentage', models.FloatField()),
                ('points', models.FloatField()),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scale', to='core.instructorcourse')),
            ],
            options={
                'verbose_name': 'Grade Scale Entry',
                'verbose_name_plural': 'Grade Scale',
                'ordering': ['order'],
                'unique_together': {('course', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='OBEStudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='core.obequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obe_marks', to='core.coursestudent')),
            ],
            options={
                'verbose_name': 'OBE Student Mark',
                'verbose_name_plural': 'OBE Student Marks',
                'unique_together': {('student', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='instructorcourse',
            unique_together={('instructor', 'frontend_id')},
        ),
        migrations.CreateModel(
            name='POGAMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_mappings', to='core.graduateattribute')),
                ('program_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_mappings', to='core.programobjective')),
            ],
            options={
                'verbose_name': 'PO → GA Mapping',
                'verbose_name_plural': 'PO → GA Mappings',
                'unique_together': {('program_objective', 'graduate_attribute')},
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.coursestudent')),
                ('unit_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='core.unititem')),
            ],
            options={
                'verbose_name': 'Student Mark',
                'verbose_name_plural': 'Student Marks',
                'unique_together': {('student', 'unit_item')},
            },
        ),
    ]
