# Generated by Django 6.0.6 on 2026-06-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_dept_admin_and_course_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], max_length=10)),
                ('course_codes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_plans', to='core.program')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_plans', to='core.deptadminprofile')),
            ],
            options={
                'verbose_name': 'Semester Plan',
                'verbose_name_plural': 'Semester Plans',
                'ordering': ['program__code', 'semester'],
                'unique_together': {('program', 'semester')},
            },
        ),
    ]
