# Generated by Django 5.2.8 on 2026-06-27 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_semesterplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AdmissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_officers', to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Profile',
                'verbose_name_plural': 'Admission Profiles',
            },
        ),
    ]
