# Generated by Django 5.2.8 on 2026-06-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
