# Generated by Django 5.2.8 on 2026-07-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_semester_closing_and_final_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='reg_no',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='course_code',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='student_reg_no',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='instructorcourse',
            name='frontend_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
