# Generated by Django 5.2.8 on 2026-07-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_indexes_to_high_traffic_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'department', 'program')},
        ),
    ]
