# Generated by Django 5.2.8 on 2026-07-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_code_unique_per_dept_and_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subtype',
            field=models.CharField(choices=[('theory', 'lab')], default='theory', max_length=10),
        ),
    ]
