# Generated by Django 5.2.8 on 2026-07-14 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fix_course_subtype_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markscategory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markscategories', to='core.course'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentmark_set', to='core.coursestudent'),
        ),
    ]
