# Generated by Django 5.2.8 on 2026-07-14 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_markscategory_course_alter_studentmark_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorcourse',
            name='catalog_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_offerings', to='core.course'),
        ),
    ]
